### ISSUE TITLE
Index Json format falsch

### ISSUE THREAD

**Issue by Koringar** [Martin1991zab/OnlineCodex2#6]
Momentan wird die index.json so erstellt:
```javascript
{"necron_2015.json": "Necrons"}
```
Mit dem Object lässt sich aber nicht richtig arbeiten, besser wäre es so:
```javascript
[{"name": "Necrons", "file": "necron_2015.json"}, ...]
```

**Comment by Martin1991zab** [comment]
Wo ist das Problem?

```javascript
var json = {"necron_2015.json": "Necrons"}
$.each(json, function (file, name) {
    console.log(file + ": " + name);
})
```

**Comment by Koringar** [comment]
Das ja auch eine JQuery Funktion, ich verwende aber lieber JavaScript Standards (for) und damit ging es nicht. Naja, jetzt ist es erstmal geändert.

**Comment by Martin1991zab** [comment]
Ich hoffe du meinst damit das du jetzt die jquery Funktion verwendest?!
